---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: auth-system
spec:
  releaseName: authentik
  chart:
    spec:
      version: "2022.7.2"
  values:
    redis:
      enabled: true
      architecture: standalone
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

    prometheus:
      serviceMonitor:
        create: true

    authentik:
      secret_key: "${AUTHENTIK_SECRET_KEY}"
      postgresql:
        host: "postgresql"
        name: "authentik"
        user: "authentik"
        password: "${AUTHENTIK_POSTGRES_PASSWORD}"

    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: route53-issuer
      hosts:
        - host: authentik.jrhorner.com
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - hosts:
            - authentik.jrhorner.com
          secretName: "authentik-tls"
