---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/apps/sources
  - ../../base/apps/blocky
  - ../../base/apps/registry-mirror
  - registry-mirror_secrets.yaml
  - ../../base/apps/velero
  - velero_secrets.yaml
  - ../../base/apps/promtail
  - ../../base/apps/loki
  - ../../base/apps/grafana
  - ../../base/apps/kube-prometheus-stack
  - ../../base/apps/metrics-server
  - ../../base/apps/kured
  # - influxdb_secrets.yaml
  # - ../../base/apps/influxdb.yaml
  # - speedtestd_secrets.yaml
  # - ../../base/apps/speedtestd.yaml
patchesStrategicMerge:
  - blocky-values.yaml
  - registry-mirror-values.yaml
  - velero-values.yaml
  - promtail-values.yaml
  - loki-values.yaml
  - grafana-values.yaml
  - kube-prometheus-stack-values.yaml
  - metrics-server-values.yaml
  - kured-values.yaml
  # - influxdb-values.yaml
  # - speedtestd-values.yaml
