---
apiVersion: v1
kind: Secret
metadata:
    name: speedtestd-config
    namespace: observability
type: Opaque
data:
    speedtestd.yaml: ENC[AES256_GCM,data:sKfvlLJ2wdEXaK3DlHLS7G6wBiIWnBn+bg5F2EHFBRfShS76Rfq9U6RUJBePA8FApUS/MaQKuuk1WXTclFNhPsWKW37jKr2G1zUGh8fbT4ufarKuxtJHXBTD1BVBnuLhnimObuVL/uD07KqdfVZFoSCsNloS+nlCdSCy/Z3afB3y7srCrWKVWDMWauOy3t4h6djXXBkobF+lsrSTcw9C5dKx/T3RtzQ+GvFbs5ZinBqftd5d4D6OHEg1+pVPfxRZIkm2VhIXDL2xJ+6v141xwMUuhqWVKoqxBzSTjNNRaT9LEpJhsA==,iv:CM44o2a/qyMBfy7INnQkBcWb9YAtNzaIxlyVUAggRbM=,tag:r2Z1t/v/Z/L5y/M9gi+J8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-11T01:16:25Z"
    mac: ENC[AES256_GCM,data:4IZ9xqQZgTFgbtWC8iGguY9OFV0wBPGqErD7y6Mp8AFb3ACPjYIMOB5+gKIzSPlRJPVcogJHezI6dZpbiXW7TsVnqIyu5d7LddVV59imVuglueE9noOY+5K1A8Edg9APr6UZ+mMlKRH7SPdcMCG7TuLulqTUVWsubR+7NwjSWKU=,iv:UJp/K2KdhZqUlfv6ToVP5ob7wNkQs2xjXCriW3kr0xU=,tag:LI2rlqERhIUmEPn6U8+15w==,type:str]
    pgp:
        - created_at: "2022-07-11T01:16:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLAQ//e60I3IGPP6tcZRrCGaQNSXhVG+W20zX9Ko2GOZAMnM+D
            983p47kly3l4qgekZ2LT/T2GJTdnDha7hnAWbPac0xwoDWmuogYyq+veO1MgFPxd
            a1EN4Jvl1N/ajdI9wotz1i6UTSP9eAZ8f3Q2FI3t6kXyVp6eliDYzlw1WY3a8/GD
            b8O+xDWcvjvguGrnl9Cav/v6BWACkq+e+6+9WREAw5KnCmWwfOfcGjgGLiMopHSe
            SPn8Ek4aZYINDjNF7G7iSuOao6kg6PRpUA//ljut/sT1UiiblHC+Hh4x/jvpwtxc
            V3palT0Kl8N+R5m4xqPtU0GKMBGstxztBUIsbBlhFGCRPg8WRXpsHsSit7Z8Vwbr
            ffvZwGRnyLFVHOMbwTCad66Z/7wpeDSE65Ubu6tkp6vKBMGON7nlZGx7B5767iux
            QhdZLNGPLKqkv52nLovhFHbMjZHQTP16BwptaREbijCnjSjO7cWA7I4tjpARJmbI
            2id/EX+dY5Qt3wgwj41uAq4f6xCVwJzrWVMSK3yQu/DI2lGKVuCk1hA3AiOkSgmH
            VQxkYzl8nWKwTLm8V0MCcpxXei7SDe/Vxgf02QoetRn7dcWp1Cu2vwbgEaz4EJP+
            IEsnukCGTUwdFh0ee0L5yFtndK6D9A3XJd339OfDGrjwqaEglVdEU+fG50GpkXfU
            aAEJAhCGWZtLohqfIPFbaEGq1cMnRuOlCDD1r9P5svvDiN7GtS3KK1S0uevPhOde
            vOFElYqtzrn7SpGXlGejGcdRnDmhTl/g6IiWsg377HeMgGvXXQWBAxI+RqNQyXGA
            lJ1VtbIjDs5C
            =ga1W
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
