---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmChart
        name: grafana
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  