apiVersion: v1
kind: Secret
metadata:
    name: velero-aws-credentials
    namespace: velero
type: Opaque
data:
    cloud: ENC[AES256_GCM,data:3e06NkunDkTb2y5OkWD01vBWF0LXn0TIft4kwKtIGThd1qVFZiW1+ewrHHEs/HsczeyprAgD7kVlt0kW2GF3FswSWSzJZ4Rr1Fd36z833XOFPmpWjSNyF/AinPxEaHY88nTc4BX/CMVZT7Y8nvh4,iv:S6Opll1e5FPdYOPLPhRXLz8bUAkm+YDyR557SlS6bRI=,tag:3JLstq5tQ0fY17KD3QR8tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-07T20:45:30Z"
    mac: ENC[AES256_GCM,data:9FvrZLepKhf6lTleT32a7ejq/1bMPDJ7i0PuE7FNNmyIXQ6fjVJY7rmf7g8uDqseHPHpcN55JzyRJxEfuxfWcclb6DazmsPPED8xWfklOLUudKNjy0ZOnJtKAC4jFds2jbwqLGGbbBK4XFj9D7fTromCvpqU2eyRJHy1+abycAg=,iv:a5eAFVz6qULv9Kk/B6pNDASo+I90GBdfOM/AGMGoG+g=,tag:CzBZmYwYsNvRTIEWTBEVLQ==,type:str]
    pgp:
        - created_at: "2021-07-07T20:45:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLARAAv2nyu59X2btP/gDlgjPRR0pq5sozPK+o1Vsfy8JubQ77
            Ufr+cIHbO1V6gZDYU2Z/L3DUPgTkxeututXLWVFxoANXvDa7r8U5H5cfa4Sp1n3A
            hmhtYZfVNadDFbAfIcquxhJB9oeKAz4Oin4rprq/R+GwSTjyeJONVoq2FB72cVXU
            C11T3f3LpW8lQ873M5scOlmsZsu+sTC9JaNFDsuNYudgJqww61gZmllFUeECAhCR
            m/8LOrwQ/uQm0g/GEKguQAj2MgVWhxSQpPJGlxLzYl/IwBlsxhn5uus/+dx9Lkzy
            81S5LETZEB90lKWOkpI6bIrOBBIXjKJlFddF7TmuUiLlzCPAYf6t+cy5xsW+rrUM
            m/LEsw8DV/iEGD2G2+TFbFBOBPlCOcrgRORDsHrwqeYCpJpH1MlpXzmROffy8oma
            nMoT/fus1TC7pMrCTLsW+0nnWP2AvKgtHFMFNLbd7fjjeNDiOa9HV1BIFR7xb3tu
            se0+9t69Smx3f2ponVhpI6p2efJDa19UEZNwINmjsMiL0uGoWwshF8a92IkaTuui
            SKob04DC3W4NRIe4aIkufVWkWHye+FJWF5W5chGQHGpjbOX2mXcDKwTkLf4n+P7r
            P5GUC3ovTubo9E8U/FyySKtciGa+nAUWdQXnq2gay72axnLBMDskgHTPZW3/EVbS
            XAHQY682YIX7OeZzwP3bR4xAIr/US4SyoM4SXXn8Bn+egfh+vbZwVbhXPLCAPuZ+
            5htRQjQGh2pxNUeD/jBpAWqgAf5O9V28F5M+nAFzkbvJBLL9kUO9C24qq7T+
            =i+8Q
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
