apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio
  namespace: default
spec:
  interval: 5m
  url: https://github.com/istio/istio
  ref:
    tag: 1.11.3
  ignore: |
    # exclude all
    /*
    # include manifests dir
    !/manifests/charts/base/crds
    !/manifests/charts/istio-operator/files