apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - openebs.yaml
  - metallb.yaml
  - istio.yaml
  - kube-prometheus.yaml
  - kiali.yaml
  - jetstack.yaml
  - ingress-nginx.yaml