apiVersion: v1
kind: Secret
metadata:
    name: prod-route53-credentials
    namespace: cert-manager
type: Opaque
data:
    credentials: ENC[AES256_GCM,data:tKkc5Fx3B5G+SbQP1QLzq6uE8/c8rq5DCwgUVZZHSWRUMxhEXt4qFll96E1vD6OOZ7bE6Mk5K+5BuvYT1JXwcPfj7+AVjp9XKf0AENPfm3/WPX730eH332SmKH5rs+/SwZ3jQi9QQ8cpiuCPzji9wEvpewTHYFXD1yGPGJmkedWOAAoVNgxe3i9UCsF5GHo3RmvGjjFNRXU=,iv:vm3RGZC6jfjdJoLaK/0G587f6WfzQG3jKKqTP42w56M=,tag:LMh0MXDV6QNlQqKSylTbNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-23T13:38:27Z"
    mac: ENC[AES256_GCM,data:3EAC2ybdraWMikTaQaX91cq7j6Y2VFYtMDeH8hPzCcAmNXdqBrbi6mNEG+sfQmf3IND1UDrT9KVJ1ryDV/2jHyeRATaCWCowtadLD2zqMUFgfk3YdsaJViMk+TlZPmcxMeY32kKj7LxVs7tekbOJ+LpRyWO2fyHuDBeDcSiKTW4=,iv:/SqhNc4bgIqtEH9TypJ5wtN5xK/NpcAlvQmP7oUtn3w=,tag:7LjAoI3t7vzGHpOr78YY3w==,type:str]
    pgp:
        - created_at: "2021-06-23T13:38:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLAQ/+NQCu9rWGU+QqKiN+UNggQpHp+viNr5cPVmMU9TlXFDFH
            BXH791yY+kGqHWZGhnTZnKLqg0Oy/rtcDvuBslx2kPfd1NVNLfb8Z2c/uhNEyN8n
            iIacvR5TGrRSP+F5TrFIlsePQdRa+Or9J6ug1odw4AoT1NydXfvIxBdqoM3HiLOe
            o8CoS5ukn8uDkhP6zg69zjQxPduP7SC7AQ2UB2FXXqhfgllBXhko2l++LrJ01e3+
            0ewEqQ9bEe1pTAqj6BPEP7GqgS07drflq/Iu7vff6gxRlkscHq8KEt1WgqDrg8OW
            Dn2CcXrIjHhQ9Y92fNT7Ip5kwLgEMEGdpqaVIpuLTPrcLXZd6Y4f6D9qGUKxQ+QU
            SQutlWdkct//tJUqLqIMhnDy4oiGL0NObrKO3ESTjsGdNSwtNxZnoz40e9icYO40
            WzgtYMZZZKmQAo3yuMJQM+AHO02T4cEstJxcOaWdkNbjA2cNoikSTdDpTqaX1AfJ
            KJBMeEvqDBxFPfx5N4+EB3V7bJShsXFkj9jtsotSflDqReJTM/U7cfePMNuarekD
            4/T3UiRPZDFi2joZlgc0Ta62iSuT32L6KmqTm1fuEGA7KifpKnA3NTfXX7PEsYhD
            LlOLov+gNbo7c5WCyxnpyzXn/1UjbJ1Ev49RO6SKjA1Y05DWxGYmRm5TlHIgLTHS
            XgH7gSKHSW2ToxLfxKm0j2YoogGnZAv/Rbr16oeHWCJc+27Sm66CafsqmYXwp/mk
            8o0vRXavfNX1cmHwQ+KK3Itvj724rrQPNtv0cqMclHLrjiVKxtbUYlmqQr2uF94=
            =JFo9
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
