apiVersion: v1
kind: Secret
metadata:
    name: registry-mirror-secret
    namespace: registry
    labels:
        app: registry-mirror
type: Opaque
data:
    proxyUsername: ENC[AES256_GCM,data:RyXuBZtKwq27TRh8,iv:RZH4frVJkOd/ujV9VYP37eTo5mC5yrZ1zNnolBO0PnY=,tag:0aGWs5NUXHfyKVKl/x8pHg==,type:str]
    proxyPassword: ENC[AES256_GCM,data:Ir/TpMnt03QMopZye8KG7IXbXTyO6kUP5cfQRFhvkdEGDL4+HBkHIuTSbvISdFYg,iv:ZcORt2U3lpj9LAuSm5k1Efq+C/CCKASPcXkjFupl6dI=,tag:SYO5DYfI+n8BLbB0M/4V8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-11T15:37:10Z"
    mac: ENC[AES256_GCM,data:nrimqGWCtnJcGjcwB30TRJgcg+rUCmQwl5/aQSzotRIXDTJx0Szz5z/+KNp81vO8T4Ctrzo+A/6vlD9JqE7Jqfx5kDmvyk++ECzMtMUjfPyDgdVo4kT49CrH+VTCiHHq53aFzIaG9KuQq3BKv3zxUOG5GZNmlltgNPY9ytrOd0s=,iv:GBzU4Z0XLvO/FxxRTT/MfEl5HuBeNQBc3NgnbnyYwYA=,tag:2FAFRcIEQGX2uUcqr3CqwA==,type:str]
    pgp:
        - created_at: "2021-06-11T15:37:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLARAAsj17cZJIlkR3lkjPL699dQDqCX34I0OnD4QRpqUwAm5o
            /i/+MgW3vgCxGTYIKaxXLvg+mo2vClrfhPVz83guhqfmWTkX/1+IhiSoRZ7YHLxn
            0B1WTNuwO0nGriecDcCMYo367GPa+eiR1FCetOpq2nDFbTCoHfdiLn8IbrJiv6kq
            KWsaCxjdDYSW3d2FlcGwrX9E6B0N6pjofBsBmU5ehbQUx8h8WryjgPuY5JqTWWwb
            9Fad2M57Y/v8x/TShCCTeMOd34gGn/mqpSqFis4lLFby6RJcENCM8Nox+mzOeOWP
            Ec8/y/SwVqUll6Rq7R2ruEUK82goIhrw113GYz3Xl9udw6G/UGdQF1KhB5b2BYOj
            BmWxorxDIunIYEv6jO1vQcWVki44wWMcMUVJpWCP1t3d+R186Mi2n82lL+tiCGzS
            B48c5VOBBcfj0+07+iq/C5J3pBuUdumLZbfpgHSccU2zqy9DwCIajcLN2mNTfA+8
            MEtA++Alk5Kw4dHysT+MtJ0DLJD22tXpEG3y5q6d3+Es8OvjvGR8hc1X0gOZNpgb
            +5kXDRRADedqFghQgaY2itM5ua6d2BptFNiE/PObMi4T9+W6VTvrjtzANSeFTfs0
            mNIhlRqKzQjyrTi+hXkydwQTlfe/+DXZSzNRG9NeOzmu0LLC3fxmFJsLHVZGXDvU
            aAEJAhXVuhABklT+LaU0ZFRPdBY3bm2Gb+f3y409PzU3FzA0nvdQLJplKfd7nATn
            IDDIu029qJnZFHQVRRMMYxGyw4WqP/gHBN8ITnhc4VsfNREa0FZHtS9UTiF7glWD
            59FxvM7PpqKs
            =uFmg
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
