apiVersion: v1
kind: Secret
metadata:
    name: registry-docker-registry-secret
    namespace: registry
    labels:
        app: registry-docker-registry
        chart: docker-registry
        heritage: Helm
        release: registry
type: Opaque
data:
    proxyUsername: ENC[AES256_GCM,data:Nzpfk+0tQzhIiaXl,iv:BI9fUaEdsOcO7fOFNht/vpUMizkCpxoRmUkOUidIdXk=,tag:kz8zYAXAA4/1kR9wAAn+1A==,type:str]
    proxyPassword: ENC[AES256_GCM,data:MiZOtb+8f/gY6J9k25JrzvKE1hS4g0a4mccS39ay3fvzAoyHw5v2kjwuwWEoV58A,iv:I0Bf8QKiI1T+o4nDBsVTtA6Kyi2gyBwi4I1Vn2kzWE8=,tag:wEmamPo70VRsYu/5hMdoFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-23T13:02:29Z"
    mac: ENC[AES256_GCM,data:G4QlGbvtrUoZvQD379qqi2hjX0Mnu+hmGmcA/etcYQU6uov0om2czFErjIn22UHk0gLzUJ8rCEfoey1CitabxKPoLhs0WYKoRnZXXlTU4WPj4oED64o34IuS6oxGQZeerMPSzx9bu6NqjXC9G+MQ3mQPACu8eoboWq//a23qZeY=,iv:51/cmz515a2zg8L3gjlJxTA1M0e0foCFQKd4zywfNjs=,tag:UNjoPG60Rzo5GEh2SlR0og==,type:str]
    pgp:
        - created_at: "2021-06-23T13:02:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLARAA24VwHQbNU1CxxNpkDkywGMpvTIj/5uvuam1CYHgackmP
            VR7+PrROR5S/oZHghAJAHMJhzLv+VZw4DDEtvEJG5JNBM/u+hhgWeV6tXEZ0Wyqn
            uYpuKWD5a0i86j7KcYHJrHQ1uftE/aFQHRImmgLyrYgrQzygXx3wL+8+bVGSJVv1
            q2VUkECScev7SIyIkbx8ajNnsmEPGPppvFDx0dq6YotYBKq9LFXWVDzDhkGEep1P
            Cf9ljyuF+vwbk4SGeC4jflTZVeQIMxe1sjTUW6fE0EFpwXs76HXihHMRAesO+M0A
            Wt6iC5/Q0TbxGFUuv2kCLb9tboThRw3ZHD/YzWi3IVpmo/YrYmYYla0Bbqw+7mPL
            3w4vENF1tPhK4Xf8IhNZDkepfF+jc/L1kwGce4f6NeGNyqREcWazAyj2I5tT/W5h
            7K7xl5UN1EXgSm5m5FE4v18MPD9Xan0CCSTPje9BtAclZHxivlMxp2ti7rskJ4cm
            lbzay/NHZaKPD2/fwmsVWf43mPwXL/XoHnooUKrbqEvzeYmM9dCBCyISM9pOuCp7
            2q/0keFUDW3Ii9OnCRdXn0hiEuEiGz3ZFIYGcgk+UTF8HIj2i6+1WxZ1u4bxRkvo
            ieY9txqaA4gGgVxMl32OzWmbqlJoujn2SMo9uyhtdiTJmwWOxK2siC/nd7vKUOXS
            XgEkbufTwRBVW7uQD3pxPccyrTg/mTbrkDeO5S0UwVKzc6O6soj1K8VwHtzBkREm
            4rYSZfvHTSrP3bWR2/lEKmTUaq0stTIIjz/+dpZdNJINtGCd9q89Lk7VKaGxJUg=
            =OML6
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: registry
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:iF8il1ob9GVwFwGFPduCThfmH9YtpWDndJl7pF9Ge4Z162MLMLHnjFyS5+62z++p9B4zYccnp1rBRtsk55QpnueAyGqZgd5RscawZbckq9cjZ3pAqlEPgK4A/FEsPbQGqmQP1FaJ4byiCMVn5BeCJhE932HDz52cLi4nqvLZx16SL1dtn5E5Sj6+FhG9+RWqDgao70hygw3six2capw0zgXZ6qLkT4zS2BXt+9rmRwLiZr3RTAN/MLktc2zfTQlIOaVPalRNA8rehn0n4VjbTF+rzE+YoaifhhvFJQfphGKaN7UnODqriwrKHS3ZlfNAqsTOysOPhZT6xu5tGLt9MpkslJLy8MjZagq/Hymcmlgon2P3gbXZO7k5HZO7S45690RbZTYaG04UQwLp,iv:QknfONnf112WrfJP2spvTkYmwtaCdnOVeM0O7jLJqgU=,tag:9EZpe17BouR2z5N/ePSQ0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-23T13:02:29Z"
    mac: ENC[AES256_GCM,data:G4QlGbvtrUoZvQD379qqi2hjX0Mnu+hmGmcA/etcYQU6uov0om2czFErjIn22UHk0gLzUJ8rCEfoey1CitabxKPoLhs0WYKoRnZXXlTU4WPj4oED64o34IuS6oxGQZeerMPSzx9bu6NqjXC9G+MQ3mQPACu8eoboWq//a23qZeY=,iv:51/cmz515a2zg8L3gjlJxTA1M0e0foCFQKd4zywfNjs=,tag:UNjoPG60Rzo5GEh2SlR0og==,type:str]
    pgp:
        - created_at: "2021-06-23T13:02:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLARAA24VwHQbNU1CxxNpkDkywGMpvTIj/5uvuam1CYHgackmP
            VR7+PrROR5S/oZHghAJAHMJhzLv+VZw4DDEtvEJG5JNBM/u+hhgWeV6tXEZ0Wyqn
            uYpuKWD5a0i86j7KcYHJrHQ1uftE/aFQHRImmgLyrYgrQzygXx3wL+8+bVGSJVv1
            q2VUkECScev7SIyIkbx8ajNnsmEPGPppvFDx0dq6YotYBKq9LFXWVDzDhkGEep1P
            Cf9ljyuF+vwbk4SGeC4jflTZVeQIMxe1sjTUW6fE0EFpwXs76HXihHMRAesO+M0A
            Wt6iC5/Q0TbxGFUuv2kCLb9tboThRw3ZHD/YzWi3IVpmo/YrYmYYla0Bbqw+7mPL
            3w4vENF1tPhK4Xf8IhNZDkepfF+jc/L1kwGce4f6NeGNyqREcWazAyj2I5tT/W5h
            7K7xl5UN1EXgSm5m5FE4v18MPD9Xan0CCSTPje9BtAclZHxivlMxp2ti7rskJ4cm
            lbzay/NHZaKPD2/fwmsVWf43mPwXL/XoHnooUKrbqEvzeYmM9dCBCyISM9pOuCp7
            2q/0keFUDW3Ii9OnCRdXn0hiEuEiGz3ZFIYGcgk+UTF8HIj2i6+1WxZ1u4bxRkvo
            ieY9txqaA4gGgVxMl32OzWmbqlJoujn2SMo9uyhtdiTJmwWOxK2siC/nd7vKUOXS
            XgEkbufTwRBVW7uQD3pxPccyrTg/mTbrkDeO5S0UwVKzc6O6soj1K8VwHtzBkREm
            4rYSZfvHTSrP3bWR2/lEKmTUaq0stTIIjz/+dpZdNJINtGCd9q89Lk7VKaGxJUg=
            =OML6
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
