apiVersion: v1
kind: Secret
metadata:
    name: registry-docker-registry-secret
    namespace: registry
    labels:
        app: registry
type: Opaque
data:
    proxyUsername: ENC[AES256_GCM,data:5VLPlYQxoXITjTb9,iv:qarRYc5PYiXQnFE3o0qR9y4aDB7QpkDHt4uN1K+N+Do=,tag:++pvxb51oY4D+Cyrsi2FTg==,type:str]
    proxyPassword: ENC[AES256_GCM,data:y1j7+gnISwnFulEGp4SZo9chgmxcEalywpg2TZeNfcXS4/TjlQJ1WOR+5QknqL6e,iv:72u8wqrAeIA4VR+reAK1tXb3RuutTZAJFDkQsj2mA2g=,tag:KMp8paJTmpBax+ubv1sUFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-22T19:46:49Z"
    mac: ENC[AES256_GCM,data:lJMFl2Hjek/Sfk5c2BVdQNn/6ig7ZV0tKt7KGULm2Msn11bYvx7iN6AK8KHyLq0gAeEwz4YwajyQxZ9hRX5UKIvia5Ew4R5WCLg+nW8XkVTKpEmLhRi/TbCfsNZwsCeT7hadIgPXsVF9KBWl1HmR4HSm4I8eP1T6qFwRfBfsKsU=,iv:men2sfieOA8dTZKGrCr7bhQytiKBgSRQRb9fP3+a0+w=,tag:1TTli4uMWI3TnDQiN9HCtA==,type:str]
    pgp:
        - created_at: "2021-06-22T19:46:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLARAAp93bT1yWlev9qztv87fa1g3XexSnozSvq7pYEyUQyLji
            /oQudAvJmvg2d4ZkMocIRTUrfA1JW6rN2AW//3eON6dXza19x8kSLgrU2JHvY7ZH
            tuHNQTANgermeXNrQMwlfxXFzNBrVyDTT/vzJveqkD10JMoMnfYQ9o4z0Z/uqzzE
            WMLJYlL03R24T8qarQrmsltPprofUWcoNVHafkDJFSyIdlxh/cHAlHRDRWO9BMyj
            40sUlY96ZkKE3pFodQT1DnZUDEE6UNhES4Zj+JfA+BuxrgVd7hGktNABc9Sr4C3i
            iJIHofJYb7ckLfpsETjiwbFi/+/qargkrIIhcU7tMjOkOzKso7PtMs9J4nSQW793
            NM9TWkHkDNwI2hL0Q4dd+kPfqZjUsiuOMqT0/rcwIrqhNZzEiYNySTd9QOTDEbc7
            xeMReYLO8EnV2w+Fhh8ZVdMfwcZsOYYiekuPekCVEbm+zP30BO2XJ5UWS3YVB2X+
            EscYNklnkjsiaAYVnh4VmyDd1o0MzXojJBBqjfYOriCu2HnQ3HcBRFoVSsxUlzd6
            T6T8GE/01NOadoan+cE0vRlnST8Mw3XyEeR1Cj+3ientI4uPXMRzRBGXgTMhWUSA
            c5XMo6Wat7Hzk0jHnSNcwCk5jvXHXU4uzoDgTUvyi43cjetvRl5sR6UgG23Qo5rS
            XgGM90CG+D2Bx6t53/fTwmiQLbOIPtqXenrtL33S2QqkLPkdwp209k9qH0gRBXT2
            KEujaoF4ub2NxJro5ic/QxTn1m4t0sWDI4rBmydVC5sJX/5J8DOCRvAhHSCKr/M=
            =Ln3B
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: registry
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:cJSeyOnuhwcGigR3U7wsT2G1NsBRn/NfrK2HwYFET4uufKhd8Ie1B3o9AjETXlFRkVZt4bU1w39p9n/VpVo58eKeVFo5oXDkGsGhALSQfJg+q4N3Dm6JUKw8TkjNVnGyiuSrnG94CuiTKwcGWfCBcqaH0+5hehVkBZ3TA6doOafDguZxO20RIqpelX4EAUuvQJj4NgAS1KQgwvvG5O/IprRU0QGl2Gy+AE5rlFJspzF9v/d7pCtROFarpQsm34NK0MgY+ZjbAyHprzY+LZvnwKyclo8uKHArhevyNM6Mi/RVu95y8G3+1U+eqFuZS/tDepw4pA4y8ma2+/JC43tBeClEGlgcmvKXfkPTFi9/dnHSLELyhaK9xAgaGB6yY6GS5hk1VqSOuofbvbTx,iv:RjotvutqDcGOeOBYEU3RyBIR9O7qnwZHiXxYqzSVaxY=,tag:KaplMGBUi6dt2tQ/WBhw6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-22T19:46:49Z"
    mac: ENC[AES256_GCM,data:lJMFl2Hjek/Sfk5c2BVdQNn/6ig7ZV0tKt7KGULm2Msn11bYvx7iN6AK8KHyLq0gAeEwz4YwajyQxZ9hRX5UKIvia5Ew4R5WCLg+nW8XkVTKpEmLhRi/TbCfsNZwsCeT7hadIgPXsVF9KBWl1HmR4HSm4I8eP1T6qFwRfBfsKsU=,iv:men2sfieOA8dTZKGrCr7bhQytiKBgSRQRb9fP3+a0+w=,tag:1TTli4uMWI3TnDQiN9HCtA==,type:str]
    pgp:
        - created_at: "2021-06-22T19:46:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLARAAp93bT1yWlev9qztv87fa1g3XexSnozSvq7pYEyUQyLji
            /oQudAvJmvg2d4ZkMocIRTUrfA1JW6rN2AW//3eON6dXza19x8kSLgrU2JHvY7ZH
            tuHNQTANgermeXNrQMwlfxXFzNBrVyDTT/vzJveqkD10JMoMnfYQ9o4z0Z/uqzzE
            WMLJYlL03R24T8qarQrmsltPprofUWcoNVHafkDJFSyIdlxh/cHAlHRDRWO9BMyj
            40sUlY96ZkKE3pFodQT1DnZUDEE6UNhES4Zj+JfA+BuxrgVd7hGktNABc9Sr4C3i
            iJIHofJYb7ckLfpsETjiwbFi/+/qargkrIIhcU7tMjOkOzKso7PtMs9J4nSQW793
            NM9TWkHkDNwI2hL0Q4dd+kPfqZjUsiuOMqT0/rcwIrqhNZzEiYNySTd9QOTDEbc7
            xeMReYLO8EnV2w+Fhh8ZVdMfwcZsOYYiekuPekCVEbm+zP30BO2XJ5UWS3YVB2X+
            EscYNklnkjsiaAYVnh4VmyDd1o0MzXojJBBqjfYOriCu2HnQ3HcBRFoVSsxUlzd6
            T6T8GE/01NOadoan+cE0vRlnST8Mw3XyEeR1Cj+3ientI4uPXMRzRBGXgTMhWUSA
            c5XMo6Wat7Hzk0jHnSNcwCk5jvXHXU4uzoDgTUvyi43cjetvRl5sR6UgG23Qo5rS
            XgGM90CG+D2Bx6t53/fTwmiQLbOIPtqXenrtL33S2QqkLPkdwp209k9qH0gRBXT2
            KEujaoF4ub2NxJro5ic/QxTn1m4t0sWDI4rBmydVC5sJX/5J8DOCRvAhHSCKr/M=
            =Ln3B
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
