apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kube-prometheus
  namespace: default
spec:
  interval: 5m
  url: https://github.com/prometheus-operator/kube-prometheus
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include manifests dir
    !manifests/
    