---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: kiali-operator
spec:
  releaseName: kiali-operator
  chart:
    spec:
      chart: kiali-operator
      version: 1.41.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kiali/helm-charts/blob/master/kiali-operator/values.yaml
  values:
    image:
      #repo: quay.io/kiali/kiali-operator
      #tag: 1.41.0
      digest: sha256:356f18f3a935b2f226093720b65383048249413ed99da72c87d5be58cc46661c
    cr:
      create: true
      namespace: istio-system
