---
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    AUTHENTIK_POSTGRES_ROOT_PASSWORD: ENC[AES256_GCM,data:UI9IpgiqxO3di8vvqKXuKWK7ULpDq5vCHlLT8ooassMflY4jxfHAPwP2JPbJMXghqFX3nQ==,iv:OfCBwJ9pW3MQls9ksYXOSl/uwfmqQ34DX5GY/eGNLdU=,tag:kUiXGrXh3NP4oE1D4u6MGw==,type:str]
    AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:cAdDCz6Ts4kk1Yt1DOZ9AYr8b3X0SyFyfwhNgO2H0+VuCssdHWqMLa561vh2NMrMg65S9Q==,iv:ZnZzWJm2pH6ncpDRv8i6lUzaUzkUFaSAOy0JU0S9bZ0=,tag:BDcfnVQv+u7L8a0P3SDYQQ==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:EVLs9Tb3h9v8Q0zTxXV7VRjVAVR/TXZcrqFQZhhCx3sNpp4bvx0uUIkKwXC6A/7RkDAY2Q9Sam4JdyVKLs0wG7MwgeU=,iv:PIDl1IAFgagkQX4AXgLrCwNs4G80pRBCj9yHskUkg2w=,tag:P9ViiRKkxp7TKe8ci2N4sA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-18T03:06:00Z"
    mac: ENC[AES256_GCM,data:mgOkYfd130oo9d42X9avxb3mYFwMKGPpipE1nkyj8CeEAxTo1zUFXSfS28LRlq/Nzq+UmQjZ2dvZMf87PPE1FAOKI//Cybw0JVyy3Qxw7JlKHP9F6zIHBOtUbADZqLFvaxdJniDxFbWK09ajpegKCYfwjH6lFAQWoo4kBvRJuFk=,iv:0+lYA++OWWDtEoB0iBNGq/FAC3jIfNhTEsOZUvkYSA8=,tag:5ztvk8zAdOnHU6jOAJgLSw==,type:str]
    pgp:
        - created_at: "2022-07-18T03:05:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLARAAiOK+iOT4qxGBplk0TvlGGepdy3hy4L6ZuRKaVaCuaLeX
            SteoIVGpXslvCGE0yLi/+F3MJKyeq9nS6nt7NoAzZpUbTcxXMcmytf8tjWsf4Cp+
            YYqyO5tC+nXgVF7cMvEqDXayYpGvMS2eVPN09px5S8iL2WNfLozlWuFqqErOU2aN
            dLSKqYygLvPDwGuBdsrV9gx8RJPLiOT6bqehsCHge13HoJPu8v+a/exi1icbjeeg
            5tUXuttnWjUQ0e6FxtAt9TzByKonA26jOh6YfnT1vxSmBvuvR/xXhbFxRVVoEM+Q
            sjUEiZ9qIrZf9GRLe7jPaYQqoexzc3gb+8CSoQ007f61kkrd7avef47C4h786lqG
            wjEY0p4cbIyL94WLkElunAg7ovI734JN10KP6mxzgAuERt5oTfOXsj6D7ynCa1AW
            9cnCIuBNH2oER2vvBmj69uk98U4womC6PQ5Qo4ESupwPuWiXCxf2X/uMuQ/5uLab
            vWyPNmgMJGNlJ6vzy1DOZINRlWR1PRx012Nwn0T701jbbM8OndUdXEYjUo2M6xnP
            837vSxtZHpzstGCk8rehRU/xBbi79ZsO6CK33uQOSjSJ1iEjYCH80Y44bPpzIKFb
            xvwQ+CzjD+Nw0QbReiGRWcnxVXII5Cb7inLhtWvYPAd1BdVzUKmMUZ838H0vccvU
            aAEJAhClKicOJh94aieBDHyw7RvCOp2GNQAoVEObEoIfptTnd1KYPqlx/qRIE94u
            Jb6Fov+vjnhWnfGmx69HQXvp7mw97biKfK3mccoLtcO9xWwmf41ycvlhdU3zKM6d
            zd27qSBeUhld
            =KkzP
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
