apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  releaseName: openebs
  chart:
    spec:
      chart: openebs
      version: "3.0.1"
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/openebs/charts/blob/master/charts/openebs/values.yaml
  values:
    legacy:
      enabled: false
    jiva:
      enabled: true
    openebs-ndm:
      enabled: true
    localpv-provisioner:
      enabled: true
      imageTag: "3.0.1"