apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  chart:
    spec:
      version: "6.30.2"
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - grafana.jrhorner.com
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.jrhorner.com

    persistence: 
      enabled: true