---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  chart:
    spec:
      version: "6.30.2"
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: route53-issuer
      hosts:
        - grafana.jrhorner.com
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.jrhorner.com

    persistence:
      enabled: true
