---
apiVersion: v1
kind: Secret
metadata:
    name: influxdb-auth
type: Opaque
data:
    admin-password: null
    admin-token: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-11T01:22:56Z"
    mac: ENC[AES256_GCM,data:cIf+FHBnfUpUrbKBQ19gVAeznIfNUQElGCEN5D6zdd/s6RX6ycYwctMvg4JnWeQyM3Jgu+Ngt/Y0BKtN9H0mYo/QDr/JP2RXvyte4p2Y0DMJ/6WIXzOTgF2gBMum/ydHM7CBQYyvA6AdTeCE8Q69laj7/wG7/JpN72djwOlfO88=,iv:Ar6LQuTlNEZOqtI1g5m9sQJtk5H1GftCGTxR8SqYQ+o=,tag:meP902xuovArDdQxkUP3jg==,type:str]
    pgp:
        - created_at: "2022-07-11T01:22:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLARAAgQq6gIOuwXFmrzSU1Rx4q01rTwmy1Tn1Eftk33kHLY2/
            CuvtCyvRxbvMGUbqb2+1ulW6sKjTp/u3ZpL6wbiDNdlhhc3ouT5AKccQoWoTuRxr
            Y5FlTLlPvI8TYKi+qMlSWT7Q7MApeSDZvjD8gXn1LQPxOWWhWTZye968ECNbs7la
            KCohSthFY7VeCorMZeoycocYCnWhcpfmHKjqtMFZgOOP2O3qNICjWqWpT6w0rXul
            SwFIOJFHEm3R7LcO6JFIG0kpqtgYT6JgUph9ENwXm4pDoAXBYR1Epu2nQk1HMOdV
            W1lC6xM0IYdLuk4w1tXj5gVoPPqdfIx+QrYznfHwGsFUnZdLF7la2lLNVVNGQ+KW
            kDxW4xYWDyszwjCoWHd/yndPDgrpgWE0OVM8QNrJR5d1fvgEQfUAiJmJ7fyGtx3G
            kSsvM24YVPYmAw6QwgAKZ07qXlWgcBgzQQJpyuyhquEJjT3yt3upU/DPzHoGddlm
            7Ht5s2wws/P89k3mCz05eNZMuJpCI6VUq0nRqenIq01idR8YuoUFcDuTlrjPNP18
            dab6TszmpFfFM7a3+6lDmMNDPoVPt1mLDk0PKXiciTJHR1vL0clbkZ7ph91u/Ml7
            EWffmtf9+hf6V2GckW5D5xeYg6JcT2rSVAiUi/KE4T1+aLs/Wann6qL/8cHO7zHU
            aAEJAhAN4FMissqBjge9vI7M597Zufd9vSAUDoUgWuMaRv3npaJN/Qc7gAk7mxVc
            VzaVyFrsZufueiI3vR76lsTiNoTwpN/bN5ZLChYaD7oSHxyOCYgyC+GVSnEMDb+3
            4oWWsRJ7dvO6
            =uJV8
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
