---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  chart:
    spec:
      version: "36.0.2"
  values:
    grafana:
      enabled: false
    kubeControllerManager:
      enabled: true
      endpoints:
        - 192.168.11.11
        - 192.168.11.12
        - 192.168.11.13
    kubeEtcd:
      endpoints:
        - 192.168.11.11
        - 192.168.11.12
        - 192.168.11.13
      service:
        port: 2381
        targetPort: 2381
    kubeScheduler:
      endpoints:
        - 192.168.11.11
        - 192.168.11.12
        - 192.168.11.13
    kubeProxy:
      endpoints:
        - 192.168.11.11
        - 192.168.11.12
        - 192.168.11.13
