apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sources
  - ../base/blocky
  - ../base/registry-mirror
  - registry-mirror_secrets.yaml
  - ../base/velero
  - velero_secrets.yaml
  - ../base/promtail
  - ../base/loki
  - ../base/grafana
  - ../base/kube-prometheus-stack
  - ../base/metrics-server
  # - influxdb_secrets.yaml
  # - ../base/influxdb.yaml
  # - speedtestd_secrets.yaml
  # - ../base/speedtestd.yaml
patchesStrategicMerge:
  - blocky-values.yaml
  - registry-mirror-values.yaml
  - velero-values.yaml
  - promtail-values.yaml
  - loki-values.yaml
  - grafana-values.yaml
  - kube-prometheus-stack.yaml
  - metrics-server.yaml
  # - influxdb-values.yaml
  # - speedtestd-values.yaml