apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sources
  - ../base/podinfo
  - ../base/blocky
  - ../base/registry-mirror
  - registry-mirror_secrets.yaml
  - ../base/velero
  - velero_secrets.yaml
  # - ../base/loki-stack
  - ../base/grafana
  # - influxdb_secrets.yaml
  # - ../base/influxdb.yaml
  # - speedtestd_secrets.yaml
  # - ../base/speedtestd.yaml
patchesStrategicMerge:
  - podinfo-values.yaml
  - blocky-values.yaml
  - registry-mirror-values.yaml
  - velero-values.yaml
  # - loki-stack-values.yaml
  - grafana-values.yaml
  # - influxdb-values.yaml
  # - speedtestd-values.yaml