apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: "6.1.0"
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: route53-issuer
      hosts:
        - host: podinfo.jrhorner.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: 
        - secretName: podinfo-tls
          hosts:
            - podinfo.jrhorner.com