apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: route53-issuer
      path: "/"
      hosts:
        - podinfo.jrhorner.com
      tls: 
        - secretName: podinfo-tls
          hosts:
            - podinfo.jrhorner.com