---
apiVersion: v1
kind: Secret
metadata:
    name: registry-docker-registry-secret
    namespace: registry
    labels:
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-name: registry
        meta.helm.sh/release-namespace: registry
type: Opaque
data:
    proxyUsername: ENC[AES256_GCM,data:LaWTfgosyhqog4eI,iv:xID1BLi1eIcW/lifnEInmDPAnLnd4nDnwfVkZYHgTsg=,tag:/xQmfOhqoX2kOUR0fdVwIQ==,type:str]
    proxyPassword: ENC[AES256_GCM,data:OctwbhIvgF6qgqbpphMxZY47Uey8FRW0Xae6k+q5JgDRzJz3+gGZARbiCR875Rbz,iv:s+7P4mJP2cSL4yFqKwkxGYMFnEOCW5FXWE5izNiYAEQ=,tag:OkYN565EQpAtY0yV8viMFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-23T13:10:45Z"
    mac: ENC[AES256_GCM,data:mfAkvGrOxGSb90nowd17g1KDYvH/IkMaG2rngNpLiJPs7fjFnfZefJ59xT9zbyfcplkE+ZnjJgHZnUSL9kmgd+W+azZBxPZI+dJlBhGwiDSU7tg4mkjlUk/eYJwgvpqHAOV9ZSo2KMzDSTh0ym4l5iHmyE//caxscyJYetOWvxs=,iv:71AAMPfsbbAsDMMs3sgfQ07afgGmGcz2Y+ZyUFRsWrI=,tag:XxpI5dcONMjoZU30FKxteQ==,type:str]
    pgp:
        - created_at: "2021-06-23T13:10:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLAQ//fWj/BKht2BWBX6k2gdQ7yG1xEPZn3EOqmSc/wL8ZtxYL
            +dgMqESJYZPRsmZsWugJJtDo4WjHddITbz27fqcfSvbaYeiYa2B3p8C47dJJsDUW
            P7LXGht/73oGo6urjS/e/ppOxlyMaRQXb0zyOqUvCwo7Oox6eueswSSGS2eHmzPc
            x008SWSzikuNJJsQX5f+K58GnQnNHooy2NBciad6TWROvNo6TaqAKpq3LEVEbdHH
            KelgZ1L8ngixzzm4m1Lf4uOgpD89iAOkH56/1ftCzTwq+u3ZmdpbOHSqORzkiiUz
            cVBM209lkMUEiwWVTGlbTIbXdqi/6ckePCy+croTTs/dpQyaDu6SJ3q7yreWpdkQ
            1c4TqfJLlhAUoB7XqFauVwkG11XP3g8NTRCCTtjfl6/RqPUkmeDZaXmrmBYgRY81
            RMz4c4FoZMdDITg6MLJzuq1LvqsQsYJQKu9DcEzfMOfnhz/AGtKtmgZYnTcglnYk
            uN2CNX5vjs+GjUTAB7g0zAO5/0HLvAgZSVWwsX6X8HUQ5Ah6z1vBS6/H1PopgHt4
            2YnFiZd29aQdGlcmofMUILHik99LYVtyZiO0kAfIbvqL3neUti6rm9MSThv/j9V+
            EZY6s9SLJ4DnyRGFx2LHBQ4s1zUa4vMWNfZoLb4za1Iky8vJnefA1yGkVwI0FJjS
            XgED1CxPRtQv5J758uE6CMcH5yVq/sx6cmeHvJhIVIzYLQpomSwKKKS1bzogrpbu
            Fe8mbXvclLQZoY66H2klRLonTbusY0sZdXrTFdGIWb8VKo3WOr66s8m2ELMTCSM=
            =okg7
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: registry
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:zGpZJKXDGOzQUd0Qp2Udp3zZgGPNm02xZZrbjGQOKhjWF3x0Sde2d6CsnfuuAHouEJIX0THaz02z5n56VtWv4YK1sW0tkTJbFOMVCxjYl08ccjVUWM8Sb3CueEn7WU+Veru5IuJFMOKh7Vp8d39lqq5xPGea3QskPd6jE9D7pY5XFLp2N3V2ub5Pu9hlvnQQT8AjBbOaPBIratbV/8lRYoAQGnHuyiTxvtKahwya7kY1TEGTXNwVL8DdGT3DvGL/eWbi16sETB9y9kA5p0ZlMoEPcA7h6ffhHqglfsRTjXB2F9f4/1UKGLxVVGdOQzTiifVPWm2VnvcVdElj64/YuYNlKuc28ZUF5NQmPfrMnEpRTVQzreYtLsSJuYNGFDxWvjgixhdpHmmCz7QQ,iv:AKNNE4d4RKMhks2jHYgczi0oOeBTQAp/tp/PsJGn3HM=,tag:WT8Uh0Zd9A4+q0rOIR8oNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-23T13:10:45Z"
    mac: ENC[AES256_GCM,data:mfAkvGrOxGSb90nowd17g1KDYvH/IkMaG2rngNpLiJPs7fjFnfZefJ59xT9zbyfcplkE+ZnjJgHZnUSL9kmgd+W+azZBxPZI+dJlBhGwiDSU7tg4mkjlUk/eYJwgvpqHAOV9ZSo2KMzDSTh0ym4l5iHmyE//caxscyJYetOWvxs=,iv:71AAMPfsbbAsDMMs3sgfQ07afgGmGcz2Y+ZyUFRsWrI=,tag:XxpI5dcONMjoZU30FKxteQ==,type:str]
    pgp:
        - created_at: "2021-06-23T13:10:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLAQ//fWj/BKht2BWBX6k2gdQ7yG1xEPZn3EOqmSc/wL8ZtxYL
            +dgMqESJYZPRsmZsWugJJtDo4WjHddITbz27fqcfSvbaYeiYa2B3p8C47dJJsDUW
            P7LXGht/73oGo6urjS/e/ppOxlyMaRQXb0zyOqUvCwo7Oox6eueswSSGS2eHmzPc
            x008SWSzikuNJJsQX5f+K58GnQnNHooy2NBciad6TWROvNo6TaqAKpq3LEVEbdHH
            KelgZ1L8ngixzzm4m1Lf4uOgpD89iAOkH56/1ftCzTwq+u3ZmdpbOHSqORzkiiUz
            cVBM209lkMUEiwWVTGlbTIbXdqi/6ckePCy+croTTs/dpQyaDu6SJ3q7yreWpdkQ
            1c4TqfJLlhAUoB7XqFauVwkG11XP3g8NTRCCTtjfl6/RqPUkmeDZaXmrmBYgRY81
            RMz4c4FoZMdDITg6MLJzuq1LvqsQsYJQKu9DcEzfMOfnhz/AGtKtmgZYnTcglnYk
            uN2CNX5vjs+GjUTAB7g0zAO5/0HLvAgZSVWwsX6X8HUQ5Ah6z1vBS6/H1PopgHt4
            2YnFiZd29aQdGlcmofMUILHik99LYVtyZiO0kAfIbvqL3neUti6rm9MSThv/j9V+
            EZY6s9SLJ4DnyRGFx2LHBQ4s1zUa4vMWNfZoLb4za1Iky8vJnefA1yGkVwI0FJjS
            XgED1CxPRtQv5J758uE6CMcH5yVq/sx6cmeHvJhIVIzYLQpomSwKKKS1bzogrpbu
            Fe8mbXvclLQZoY66H2klRLonTbusY0sZdXrTFdGIWb8VKo3WOr66s8m2ELMTCSM=
            =okg7
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
