apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry-mirror
  namespace: registry
spec:
  releaseName: registry
  chart:
    spec:
      version: "1.13.2"
  values:
    image:
      imagePullSecrets:
        - name: regcred
    persistence:
      size: 10Gi
      storageClass: 'openebs-jiva-csi-default'
    ingress:
      enabled: true
      path: /
      hosts:
        - registry-mirror.jrhorner.com
      annotations: 
        kubernetes.io/ingress.class: nginx
        # cert-manager.io/cluster-issuer: route53-issuer
        backup.velero.io/backup-volumes: data
      # tls: 
      #   - secretName: registry-mirror-tls
      #     hosts:
      #       - registry-mirror.jrhorner.com
    configData:
      http:
        host: http://registry-mirror.jrhorner.com