apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry-mirror
  namespace: registry
spec:
  releaseName: registry
  chart:
    spec:
      version: "2.1.0"
  values:
    podAnnotations:
      backup.velero.io/backup-volumes: data
    podLabels:
      backupSchedule: daily
    image:
      imagePullSecrets:
        - name: regcred
    persistence:
      size: 10Gi
      storageClass: 'openebs-jiva-csi-default'
    ingress:
      enabled: true
      path: /
      hosts:
        - registry-mirror.jrhorner.com
      annotations: 
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: route53-issuer
      tls: 
        - secretName: registry-mirror-tls
          hosts:
            - registry-mirror.jrhorner.com
    configData:
      http:
        host: https://registry-mirror.jrhorner.com