---
apiVersion: v1
kind: Secret
metadata:
    name: velero-aws-credentials
    namespace: velero
type: Opaque
data:
    cloud: ENC[AES256_GCM,data:dC+KtbAhPAkwalLVZwJEOZuxuBL4XFrazmafZ0+FvMUgmbsMr77PMDhg+LuV0axnaADslIKo7pi0PwoJ0fC6tOAdFK1UPacPVurkUH2M4T4cFlCfc3tsVPu9LdFB0bLc6y4NMqqdYpLbm7WyI16jLqS9p9kIm/x1aD0oRRDIRHxS5B4Ld1zFKoLVpMaQTtF6oCUqog==,iv:9pUDWssvEMxz5Hric2FNSqUZ3y7vA9t3qYKVKsVjevs=,tag:Xe3sqh08TliZzANEkQ5QPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-13T21:02:58Z"
    mac: ENC[AES256_GCM,data:ZvXLASMr69c6ol3RWCuDu/Nsf+R79y06J0nKZl69JW+QPJuex1MyP6Q5kSTzr5hpvsv5W8G19t3b3WpAZzFVWbLuzpxPixleyt1qfqup6x4iZ9wOlvNPiERf02s68PaTiw77gmWOVNJ9EO+6CZq4OdeKTZrbRM2PqEOkPpA8AXI=,iv:5S0SPPe73BkeR00OZXbM6v20K5BuUgGilW2dz3wTZ3g=,tag:M3HG5AKWGOYAxOFUkf61gA==,type:str]
    pgp:
        - created_at: "2021-10-13T21:02:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLARAAtpM3cloPA2ill7dKwVRWMAUp0DhYLbGHuxPDbNVgB8Z/
            1w2QWHJ6hRPQ1A2KZFvFgu/7H5MbPz5e0Zk86MwGG9jst85VqO2Mo7uMzbG1ctuq
            JrmUROy6mzUGwPR4eE7yifxjZ5Mr9k29mLFDvZ09bByMSZP7TzFt+HpMeX7BRvGN
            xHZ8pbbiDJfLDXgbFx5h5vpVOTtdp+vw7yAeBC/+qEV+TSVIar00fPOcMAZXnw4J
            PsZakWD4vVLYDBiS/yn0rJuTuJprMfRCGQOhTcDNOGijKzQ+xx/iu/KgIBMNoFHi
            j2Dlaai/PqACZyUM2JiYBUYeprVgT1IS99cZSoAMWIJL1biwBEDzHbnWFrL83rEb
            hRwgBRxTx6wOyf5V2gMtkLZfbz6dZOSyx1K3Vu0ijE5+6BFLuJyXlX2xU1cvBLJc
            v3GjV+RX2fq9Rqlf9obmTfPBPCpD0dYhdcsFwKAymsHWk0zqQ/8NYQJu7/7s/E6r
            qqhzL36+AzXIpy1U+XBRJJ6o5RKcEF9G6cPT027Qphn6oPKxDyDRtPqqtIEByjgK
            YDewRY5z+OmjpH3rsSSl5HHDVdL5DmIVGPCeADN+TVWd7OIlIFQPgKLII4KdKogJ
            0gzaGuCXIsfyG/Vf7+lh+JNMG4HKAqPTMnzzSuTiUenHEQxuxPvk1Km2NqItPAjU
            ZgEJAhWetfm9nfjYJK3G04FAkWg7w0OnCFYlrF3HVuwfUSqs2HpsImSF9C1MQ88+
            X5FdL5o3tg7F84PfM7l8E19kBA32pa4i8go4zkIX7VnvzuSqNGsY3U1fJJBeOSWn
            GnHP917IPw==
            =gW7i
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: velero-azure-credentials
    namespace: velero
type: Opaque
data:
    cloud: ENC[AES256_GCM,data:LrnwCqZxb4JX03UEBnyXrKG6jfoObbXm+1VU0lkuglsw7eZkD5qpyYi/BZg6qMYUGzwYnd8vcoGrUSSiumvg7dM3lI8oBvC8QFEE71bTfULceHj70vVLiR1832ZERi2Q8Upp1JeSMIb8bEjAYeqLgeuxXLMy4vdzqo27xSqT82zoJ1pywxfHICGrApPhRGm/mTrXT5Qyv+TmX/oTtP28RlTuQd3P8kwKbZOFGRu+tNsTZqPsvqCg93fwT2uvvM+Hb56qa8xiItbO5WLADAvMFmFGs21boZOQRDBlkCsVa8TGoTT/NXZB65RQBfPXNMes0wuW9zhxyQdk3MXQ69ayCsm+lD1aHD4EiRDXGX5FZYV5djJ1kTOfJxhF6hgatPFwenVcqcHziwx7jGSjpxyLKUZxeKKKuIRFdV8peD1oVwhDqwwHoEhXr4Xp5pVi8OHivAgcIBmSFOnXUX6oAZfWbeAHH31fAtqfKTGcGMiId/sj2eZfc2mfeG4shE2WOfziBWCaYKpNQL0pFDhgwj9lbfivqiNOayBY,iv:bZ2t83I2lkc5rrdO/X0pSC+oQ6Wl4LgRzSrxDwOOyMw=,tag:qNmJMdsvlUoOVmiserJJQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-13T21:02:58Z"
    mac: ENC[AES256_GCM,data:ZvXLASMr69c6ol3RWCuDu/Nsf+R79y06J0nKZl69JW+QPJuex1MyP6Q5kSTzr5hpvsv5W8G19t3b3WpAZzFVWbLuzpxPixleyt1qfqup6x4iZ9wOlvNPiERf02s68PaTiw77gmWOVNJ9EO+6CZq4OdeKTZrbRM2PqEOkPpA8AXI=,iv:5S0SPPe73BkeR00OZXbM6v20K5BuUgGilW2dz3wTZ3g=,tag:M3HG5AKWGOYAxOFUkf61gA==,type:str]
    pgp:
        - created_at: "2021-10-13T21:02:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLARAAtpM3cloPA2ill7dKwVRWMAUp0DhYLbGHuxPDbNVgB8Z/
            1w2QWHJ6hRPQ1A2KZFvFgu/7H5MbPz5e0Zk86MwGG9jst85VqO2Mo7uMzbG1ctuq
            JrmUROy6mzUGwPR4eE7yifxjZ5Mr9k29mLFDvZ09bByMSZP7TzFt+HpMeX7BRvGN
            xHZ8pbbiDJfLDXgbFx5h5vpVOTtdp+vw7yAeBC/+qEV+TSVIar00fPOcMAZXnw4J
            PsZakWD4vVLYDBiS/yn0rJuTuJprMfRCGQOhTcDNOGijKzQ+xx/iu/KgIBMNoFHi
            j2Dlaai/PqACZyUM2JiYBUYeprVgT1IS99cZSoAMWIJL1biwBEDzHbnWFrL83rEb
            hRwgBRxTx6wOyf5V2gMtkLZfbz6dZOSyx1K3Vu0ijE5+6BFLuJyXlX2xU1cvBLJc
            v3GjV+RX2fq9Rqlf9obmTfPBPCpD0dYhdcsFwKAymsHWk0zqQ/8NYQJu7/7s/E6r
            qqhzL36+AzXIpy1U+XBRJJ6o5RKcEF9G6cPT027Qphn6oPKxDyDRtPqqtIEByjgK
            YDewRY5z+OmjpH3rsSSl5HHDVdL5DmIVGPCeADN+TVWd7OIlIFQPgKLII4KdKogJ
            0gzaGuCXIsfyG/Vf7+lh+JNMG4HKAqPTMnzzSuTiUenHEQxuxPvk1Km2NqItPAjU
            ZgEJAhWetfm9nfjYJK3G04FAkWg7w0OnCFYlrF3HVuwfUSqs2HpsImSF9C1MQ88+
            X5FdL5o3tg7F84PfM7l8E19kBA32pa4i8go4zkIX7VnvzuSqNGsY3U1fJJBeOSWn
            GnHP917IPw==
            =gW7i
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
