apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  releaseName: velero
  chart:
    spec:
      version: "2.23.12" 
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.3.0
      # - name: velero-plugin-for-microsoft-azure
      #   image: velero/velero-plugin-for-microsoft-azure:v1.3.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    configuration:
      provider: aws
      backupStorageLocation:
        name: velero-backups
        bucket: velero-bhu0exzeqd0eghv
        config: {
          region: us-east-1
        }
      # provider: azure
      # backupStorageLocation:
      #   name: velero-backups
      #   bucket: velero
      #   config: {
      #     resourceGroup: velero_backups,
      #     storageAccount: velerod1ea957d1ccd,
      #     storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
      #   }
    snapshotsEnabled: false
    credentials:
      existingSecret: velero-aws-credentials
      # existingSecret: velero-azure-credentials
    schedules:
      daily:
        disabled: false
        schedule: "0 4 * * *"
        useOwnerReferencesInBackup: true
        template:
          ttl: "48h"
          storageLocation: velero-backups
          labelSelector:
            matchLabels:
              backupSchedule: daily
          excludedNamespaces: 
          - velero