apiVersion: v1
kind: ConfigMap
metadata:
  namespace: network-system
  name: metallb-config
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-weight: "-1"
data:
  config: |
    address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.11.50-192.168.11.99