apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: kube-prometheus-crds
  prune: false
  sourceRef:
    kind: GitRepository
    name: kube-prometheus