---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sources
- openebs 
- metallb.yaml
- istio.yaml # DependsOn metallb
- cert-manager 
- nginx-ingress # DependsOn metallb
- kiali-operator # DependsOn istio-system
- prometheus-operator