---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources
  - openebs
  - metallb.yaml
  # - istio.yaml # DependsOn metallb
  - cert-manager
  - ingress-nginx.yaml # DependsOn metallb
  # - kiali-operator.yaml # DependsOn istio-system
  # - kiali-server.yaml # DependsOn istio-system
