apiVersion: v1
kind: Secret
metadata:
    name: velero-aws-credentials
    namespace: velero
    annotations:
        helm.sh/hook: "pre-install"
        helm.sh/hook-weight: "-1"
type: Opaque
data:
    cloud: ENC[AES256_GCM,data:co1n5MfJE/4e6b8fLzPeph8UPblxY4iI3VFWQnL4bfBBV8AsNpXLOEzTaWyscDbFdB2SGtk+78y/HgXwkm7k7MPkob+GLyzslZlNaLphayDbm5eZC1Vy7VoDiVNTwdwtTODqerRrH9MAWkHvgJ2Fl6HO9Wrs/vK0AE+26YkLLdTTrDZHiX53hN0bOxVWxDtNHsxurw==,iv:IXpQxVttEXZvCmlUzslu/EQuCo5/igu0P/ujBdPHCeU=,tag:GHXPHSRFuptA/z4qnHQS8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-08T14:49:11Z"
    mac: ENC[AES256_GCM,data:eLUGL0GdeSgknVLxJ/JnyJhk0mWZnkl7fvIAjEGdttm1HFJixIhf9TZ6Hrs9lg265Gpx3NDMddGbjrxEZ7t0m9ug58lrh+vsVLt2/Ws2TVC0ng9CJb1lbCCq8raSZnltK4rKQgmueFZ2y+OTgWQ+Gio7iwhKlYG8X7qQ0n5c0sE=,iv:kIIx2ajEO8xKhDPt0E/nTo3zvvXniwTX7xohZlzbdjg=,tag:mAtzM+pQ0nfeTuEmAdhPDw==,type:str]
    pgp:
        - created_at: "2021-07-08T14:49:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLAQ//RCqhsiIF4ZWg9m232WBj5VJvWJXipYqgiKt/w+eu/ykp
            y0gqQ8B2iNYfeHSdqnEFV9o7n7b7UW2CJkotJmzO8HUc5JJ6aYdtNjVphpIfTJwo
            sylI8wSQPdsV9259Ulj2t0cTUtaa3W/hIny7s1EHUB/2o0oRNQF+PS503maxAUry
            62Dx2q6YUUK1oKJAj1T8I5hJ75zMOa8MKNLotDPfF/KVUXEQ/sGC/RRf+ptIOY0z
            TwSpwHaOz7rt9cN7xyLpN0uCVn+YHz5GpGFAV5nbyxwzDBILGd3bBzcFNd8PE6pN
            6EoZovCfNf3eTu9t80m4+fzGzi0dZffI3BY80zM390kNwtU1f/D25u9EchSYGDIH
            wgZpVkIu3PmF8IJ8RjpmWBTJsKTT5QCFE3RHesYUxU343UEu2s9dNgONzogoCn6D
            hEXljtAE7IBtN/YWsTonemz/AGDByZfbcN6GCuxSgl3UmdTmQKJWQSiujNf+hFTT
            9PnwZiBSDU2qAUi7rBQ3SJOWysgueQRNJhrm7xZI7RrfBIKJgGhVV4nENEJk+gOp
            ++1v6tV4Gquex0no9ZOV6Pii2jlic5iR4MBkp5I9AHAnZPKA3uKQFHbmXnRDinGE
            BQ4mUvB27rYEF+cIFOLr8SEgt7GLmi6L8+QmnsxfsNKc3n04b6uo1wBsz/yET6vS
            XgGLjrGX9rciTYE3sjDUl8BNcihzsgdeZ/4eWeqZhRGSM86FINk55EqG7+ibcM/J
            MHqBAFz/0PQfa8EQ6/1t4TMyChq7hSdWLN8ipBQqp2nya5STps4o1/UQg35lsg4=
            =r7l3
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
