---
apiVersion: v1
kind: Secret
metadata:
    name: prod-route53-credentials
    namespace: network-system
type: Opaque
data:
    config: ENC[AES256_GCM,data:J1XtdCIIw1l76fPvQL6ra8Fzc6EhORLWZsBmnGiXSIoyJR7Fr/XHl/1b6IZnOOp1Og1OI1WQKtv05u3iH7IuUPv6wEGKeZqrxTqexOAIfXA/kB9ItNrjOcxFzdo4BpJbzuxWboHOvYKXEhxE/I+ggGGF7YslyBMEOzYztwls1UERK8ZikPCK4MVGhT9/PFTMWLmHo6qJfCg=,iv:4ePn0fQmLfzqiAUmb1s0rhBXVBAsufynpirz5mXkAcE=,tag:JpHFxQwgYB25l4PAkfuXnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-08T17:46:53Z"
    mac: ENC[AES256_GCM,data:P1aYzXqfMj75RAdhK2aNUGaLDz4hVyfJITCTOQY0Rhect9h2yYtzSUhRjoH2UM/AJgQHZnGAGjyN4Munp42zPeMOTvq/K3TUbIqHG/TOaSVuyya20J9bL/Lt7hQf3iWgGKb4wfG87+L2ESRW6vgb3z8ptZbgKB9P7ffhCejh8jo=,iv:DIucN3vONinvVGF3mDNxpjn3psS45hcnHTLsppCQr6U=,tag:1KZ+BbgIeuamOGoTCsEHNA==,type:str]
    pgp:
        - created_at: "2021-06-08T17:46:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLAQ//e30pKPoLKjtPjd9e0/ZS0bSdwVALGxT6onngIrKFZfoC
            Ll1uL8OA4GUuKNatz6gOe4OjQLJ4ORZlGArvL/cy70uqCRWljvGOL0zcZj3RnSO6
            G0Pfgyaph5sLcSQRee9kFrARZk9EO8aOXg3rOXRNG2o5EzcEc49tvLHrRXTWa5uy
            LPbXowu9JAXITWXM71DYehUsiK5KgyWNLzcgYUGoYN/JCQ2N/EH5CL+6Dw97nx57
            lN8/NdTUp9JcbqGazkYai1THbMjHs1/cm0mqiOzDQqyN7YgDVi5bqHWMNz7LDxyd
            htogI9j7oUnsk668VflqCE89pv9+bEv5OIuIc/YcitUYvyoRUi7eZRGP0/BekOTc
            Cjrh20CBIuPLP5tiNFJ2DvCxL28e3C3apqpzG2hTxGAtmsh7FmCrtP8zvSMPr4Jk
            U0Qj00B5yhf2C5W4k1bjzlwrP5vZbhSEj8/h+aum4wqbazwynRWB+fPb6BpPdpz5
            nOe1oPa/lR/JIuAokSQ6+/cRkXUmnyHto/7wgAbpeAU79ZehKUJBccnHtmI1y5TV
            gWMxYgMuac8MTo14YCFMDckacYnB1ylwVHzUaWJuuOwgmB5B/X1Js1McwTRyBn/B
            L2e+5G9fMpsI8IVKW+A8LIcX5mYu8sxbl4WZVDzPZnM3CzMXFneF3Yl+oGRwerPU
            aAEJAhWKP0UU1JBzXbDnNCF7VHFwQGnaB5lkVDNcJybUb+lquvYqGNNJGGwOz2wd
            mOyFjmGL9qloOhRnAeSv2y5806+Tt5M6JsxGzX+i78e8NIGEEj0ZnaEd/FDzhA6F
            M7iSDij0e+yt
            =HSlE
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
