apiVersion: v1
kind: Secret
metadata:
    name: prod-route53-credentials
    namespace: network-system
type: Opaque
data:
    credentials: ENC[AES256_GCM,data:xUwTGGuzWUieblz2bZEVYL+ryvJB5kJseILthUB9a8zmk2OOgcqog/bRExkn2pl1tj6rnnAfYZsQSo+JAfVLWlUSNNBfLcDPmuQyjAkADfeqU3M9lw8uyiX58r885Sw8n4aE9V0ll/0U2abJwpam3bbqa7ULfNRTVNAdH0Kyp9lZYYCVyWQMJuf6gPHLfWdb2LWsXAS/,iv:cFBgwhx3fGtAEQ6yYojN0iyzYVjMjB5SchCNkbc6e9c=,tag:TW1u0Yfgw+UxK/wCaRxbAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-23T13:32:09Z"
    mac: ENC[AES256_GCM,data:MOTZ4zEw8zSweDJZ5IiMRhXZkuKIGu+NgbmLXY2J89vDh9WkS5ljWRf1jhw/kQRh/abFMAnTWa3B4qP4LSYPJKiCvBG3PHmvY4VaWPUUvV53LZWH/JKL0Xl8Ou7tv5k5NoiHHnFl7Ma/jIdD4yC1BpmApzuYo6Nt9jWLNYuzLXY=,iv:1JVOYzquVHZZ66Y0ux/l71N4Kh/5BPQdrwS6hPjJvoc=,tag:4B8IQkcbwRRZ9Hq74zPvdg==,type:str]
    pgp:
        - created_at: "2021-06-23T13:32:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLAQ/7BUVC+rMdqtx3bQ4ASLgGnS1VRvsg0drnT2VZjADyFgbz
            Zwyo4kbjU4RUB4kCpSX4UwBXHzHZiwTzTsBNgraa93EzMqZB5zc1lVaJjsWjvERM
            GKyqVVzPjhA6U+/eVc0wdjWd7Fti5ErxKxNdw/SjR+YaprqIPJTr1Fs4HXxo9Xt8
            cteek5mnf6ucfE9cGtvl6T/cunS9zBZMiR+1hlaU3qwog01L2ygx5l5dpHMKcBp1
            JRbTc9V9xXfTgmkxAgvjTb2tZAPRH/Lx9j3a3BbZDx3lCyyejdrt/usVMOxP0mRy
            hEevCi0OEve3EOzcG3P9JvI11Oa6kUimHx7sgz4qhdSnZilGKL9H+JVcDA3gRrRn
            L7JiezXMXT/UPwP217+PB/gBa7ahmcSZcqySCyBnxBy3dJuLqXghulLxgkAuibKg
            tUoO26wfxBw03uQi81wO149asxA8AtaQSvyXpIoYiYUtzQYlBLZCtNP6hnxPxDvh
            rWxo0SmOAFZHeyUitG/RtO7GZ9W4dkcqvc4EsUSr3STiC4sCxts0U/OD8itsgcfw
            r2SZRj3Mwc5A3B73lRa3qA00qs+8DJ70RHOglrbQ/yeDYaIrwaL+ZDUKjz9SHO5w
            B6sfKp48W137dZKrfmWCG27ojhLnKq8LlZV9lxAd/QUJ7hGnM9kLrJrH0xy9eejS
            XgHC7snIUPP1Kl1zo6m4KaQlOvqAwsjAUc/DE34t/NisjiiqIIWjiPjSHU1pkEPM
            QGmmweFX6JXGsG9PfcjKG6kI7HFaWIoQETQbJ9lNrMqSvAatVnu2YurYGI0yY5c=
            =JdoY
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
