apiVersion: v1
kind: Secret
metadata:
    name: prod-route53-credentials
    namespace: network-system
type: Opaque
data:
    credentials: ENC[AES256_GCM,data:58X9M7CkZrFVRUui4PaU2gOBB3iv27pr6zcGR2Zht0N2YqeCwDDLOoP4fPcQwsfxvMnPHuMa6KUT5Dc9JiAJCT9SjBoeuMVaPJG/4aDqrvyLc4NttMVFiDNJLJSigbeiV0R0g+DoRaJwZJDzuBVL,iv:OXghLdJASLq1HT8X9ETd1qKJ7Gc7lCKOP9qwYMbjU7A=,tag:Sg9MmPnmmGW25rJRB9IIAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-23T13:28:48Z"
    mac: ENC[AES256_GCM,data:PUZH1jZJU4Ta7apDkdgCV3xm+MXuIyX6Uo/7QZgN3x97vadNY97PJIlTsKnOmwPR8f/lr2W9G+8kao9cv7vP8dQY8UvZPEQZdhkt0tGx/sOtN/cgS1RTwUQ48VvdNLF+bLuf15v9Gu11vdceLPhI1eGLpiG6b0tqdJI1PUSrSys=,iv:TJrYkUTRF834BQs/d+UwOSDJfqy/2wlT5i86tDDVwFo=,tag:UZaYmsqMS7giqwVeqsZjDA==,type:str]
    pgp:
        - created_at: "2021-06-23T13:28:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0mik9+oJJOLAQ/8CRUruzfRGJhCxrUMtN0SnAZGjL2uhOK9HChOHk3xUl/U
            DtdSBbVihtPwwvlqmC5lMFf9fOfw12XzOd6gkIh/wDERUxabINKXlvdljHv3diFW
            f/am2LO0U37ADWAyHbG5IkH19GXTRyCNoyM8Yj38WaeVpCzgayHXg0nNPYSQdx6C
            rCYFRw6dKVpYIRYlFyh9b6RjCA6o9k/LR8newSiU1ocbTN/FMvuQrVujazYQOtJs
            2aGJfEE59UFSwEVzcVfk6nGVvKt+bEm1Pyh5A9ZGPsFy7rXDTOYOJXPL87MZR/bT
            fmtC5wM8wiFmninC1IGx4Cy4vrIqdk/dMgM/Tj3adqZ7EDQSukOrI9Bzb+CJl7Ir
            comym1bOJr1ceXv1Ya8OeaZf1ITtL/SEoqCpaQquzjnMPyUKcWaYBD43fkVozpgZ
            d75Lq+PipYVzgBqA5y3QYSnOh4jgW2zDFZZNbvWUkjMjLbiQ/veJkd+LB0Q5mB8b
            0ISP0u/P1lZqbq6TLYognqNVEC4HwKfwQ6qqAgttdrgh4YIRmjnk1BnqUEyqwhbv
            1V/L2qE1nx3VjOSEADmIX+nci3uOF4OfqtYiun8CxuSpMDnEj7J8N/5ToQ39mwO8
            aPok44ZIX0fsoC/iNWVsqt3dinfXSXvNtn6cjPBXVdhcOqLyuAPa/q3JECJjTwPS
            XAHbMePFte3yFQpIhp8F3bvKmO7degB9P3Ni6soRPsBvC8cfS9r+nxrdm7peWiSI
            +/kpu+J7Jm2HbS0bwsA53DhU4iRGR72EfxcxqKRvqtYjFXTzIScGZwJDq+4n
            =9qhO
            -----END PGP MESSAGE-----
          fp: 532458423DABB727A756D856F1F771FB906E1D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
